### ISSUE TITLE
Determining required memory for decompression

### ISSUE THREAD

**Issue by djn3m0** [WangXuan95/TinyLZMA#1]
Hello,

I really like the simplicity of this library, but there is something i cannot understand about the decompression routine,

```
    switch (mode) {
        case 1  :
            dst_len = DECOMPRESS_OUTPUT_MAX_LEN;
            break;
        default :  // case 2 or 3 : 
            dst_len = src_len + (src_len>>2) + 4096;
            if (dst_len < src_len)                        // size_t data type overflow
                dst_len = (~((size_t)0));                 // max value of size_t
            break;
    }
    
    
    p_dst = (uint8_t*)malloc(dst_len);
```

Isn't there a better way to determine how much memory is going to be needed for decompression? Do we really need to allocate a huge memory buffer(512MB) to decompress?

Thanks

**Comment by WangXuan95** [comment]
Hello,

If you don't want to occupy too much memory during decompression, you can actually write bytes to a file while decompressing (using the fputc function in C language), because LZMA decompresses bytes one by one (rather than out of order), so it is very easy to achieve this.

The reason why this code did not do this is because I do not want to introduce file read and write operations in the Lzma decompress function (tinyLzmaDecompress). I want TinyLzmaDecompress. c to maintain independence and try not to rely on <stdio.h>. Therefore, tinyLzmaDecompress writes decompressed data into memory (array) instead of directly writing it to a file. After decompression, write the file in the main function.

If you want to write directly to the file, you can modify and use it yourself (all usage should my GPL3 license). I do not intend to make such modifications in this open source repo.
